# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecdac3aefbb1b65dec6d10c09f7ad1b7f0358bbf6362dedf1a3134e4d6f95b9893931e4d8b05bc6e207ae03dc3485bfea129b12643be8157a4de603f4064aba6

test:
  secret_key_base: 5fc9dd58c4ddf676d185faded719e8b5cdbdfd5168d1ff73d2f3c8b1051d5cdaee79c33cbba32e86d7a34acde10f6c90fa51707675360d451b5a3224a4021f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
